name: Update Worship Meter

on:
  schedule:
    - cron: '50 23 * * *' # Run at 23:50 UTC daily
  push:
    paths:
      - '.github/workflows/worship.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worship-meter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Worship Meter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          python scripts/generate_worship_meter.py

      - name: Update README with Worship Meter
        run: |
          # Define start and end markers for the replaceable section
          start_marker="> If I miss a day, I owe her 10 cuddles and a foot massage. No exceptions."
          end_marker="```"
          
          # Create the new worship meter content
          new_content="$(cat generated/worship_meter.md)"
          
          # Create a temporary file with the new content
          echo "$new_content" > temp_section.md
          
          # Replace only the specific section between markers
          awk -v new="$(cat temp_section.md)" '
            /'"$start_marker"'/ { 
                print; 
                print new; 
                skip=1; 
                next 
            } 
            skip && /'"$end_marker"'$/ { 
                skip=0; 
                next 
            } 
            !skip' README.md > README.tmp && mv README.tmp README.md
          
          rm temp_section.md

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Add both files
          git add generated/worship_meter.md
          git add README.md
          
          # Always commit with timestamp
          timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
          git commit -m "update: 💜 Worship Meter - $timestamp" || echo "Commit failed (no changes?)"
          
          # Push with force to avoid merge conflicts
          git push --force || echo "Push skipped"
