name: Update Worship Meter

on:
  schedule:
    - cron: '50 23 * * *' # Run at 23:50 UTC daily
  push:
    paths:
      - '.github/workflows/worship.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worship-meter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Worship Meter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          python scripts/generate_worship_meter.py

      - name: Update README with Worship Meter
        run: |
          start_marker="> If I miss a day, I owe her 10 cuddles and a foot massage. No exceptions."
          end_marker='```'
          new_content_file="generated/worship_meter.md"

          NEW_CONTENT=$(cat "$new_content_file") \
          awk -v start="$start_marker" -v end="$end_marker" '
            index($0, start) {
              print;
              print ENVIRON["NEW_CONTENT"];
              skipping=1;
              fence_count=0;
              next;
            }
            skipping {
              if ($0 == end) {
                fence_count++;
              }
              if (fence_count == 2) {
                skipping=0;
              }
              next;
            }
            !skipping {print}
          ' README.md > README.tmp && mv README.tmp README.md
