name: Update Worship Meter

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    paths:
      - '.github/workflows/worship.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worship-meter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Worship Meter SVG
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          python scripts/generate_worship_meter.py

      - name: Commit and Push SVG
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add generated/worship_meter.svg
          git diff --quiet && git diff --staged --quiet || git commit -m 'update: 🛐 Worship Meter SVG'
          git push
