name: Update Worship Meter

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight UTC
  push:
    paths:
      - '.github/workflows/worship.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worship-meter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Worship Meter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          python scripts/generate_worship_meter.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Add the generated file to tracking
          git add -f generated/worship_meter.md
          
          # Update local branch
          git pull origin main --rebase --allow-unrelated-histories
          
          # Check if there are changes to commit
          if [ -n "$(git status --porcelain generated/worship_meter.md)" ]; then
            timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
            git commit -m "update: 🛐 Worship Meter - $timestamp"
            git push
          else
            echo "No changes to commit"
          fi
