name: Update Worship Meter

on:
  schedule:
    - cron: '50 23 * * *' # Run at 23:50 UTC daily
  push:
    paths:
      - '.github/workflows/worship.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-worship-meter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Generate Worship Meter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p generated
          python scripts/generate_worship_meter.py

      - name: Commit and Push
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          
          # Force add the generated file
          git add -f generated/worship_meter.md
          
          # Simple commit and push without rebase
          timestamp=$(date -u +"%Y-%m-%d %H:%M UTC")
          git commit -m "update: 🛐 Worship Meter - $timestamp" || echo "No changes to commit"
          
          # Push with force to avoid merge conflicts
          git push --force || echo "Push skipped"
